### ISSUE TITLE
Invalid type for parameter Tags[3].Value, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>

### ISSUE THREAD

**Issue by bogdangi** [InnovativeTravel/humilis#19]
Hi,

I try to run examples and I setup new virtual env with python 2.7 and then it returns this error
```
(deployAWS) [~/tryIt/deployAWS/humilis/examples] (master)
bogdan$ humilis create example-environment.yml
2017-03-29 13:03:41,247 humilis.layer INFO     Loading /Users/bogdan/tryIt/deployAWS/humilis/examples/layers/vpc/meta/main.yml.j2
2017-03-29 13:03:41,254 humilis.layer INFO     Loading /Users/bogdan/tryIt/deployAWS/humilis/examples/layers/instance/meta/main.yml
2017-03-29 13:03:41,260 humilis.layer INFO     Loading /Users/bogdan/tryIt/deployAWS/humilis/examples/layers/namedinstance/meta/main.yml
2017-03-29 13:03:41,270 humilis.layer INFO     Loading /Users/bogdan/tryIt/deployAWS/humilis/examples/layers/streams/meta.yaml
2017-03-29 13:03:41,273 humilis.layer INFO     Loading /Users/bogdan/tryIt/deployAWS/humilis/examples/layers/streams-roles/meta.yaml
2017-03-29 13:03:41,278 humilis.layer INFO     Loading /Users/bogdan/tryIt/deployAWS/humilis/examples/layers/lambda-role/meta.yaml
2017-03-29 13:03:41,279 humilis.layer INFO     Loading /Users/bogdan/tryIt/deployAWS/humilis/examples/layers/lambda/meta.yaml
2017-03-29 13:03:41,283 humilis.layer INFO     Loading /Users/bogdan/tryIt/deployAWS/humilis/examples/layers/lambda2/meta.yaml
2017-03-29 13:03:41,287 humilis.layer INFO     Loading /Users/bogdan/tryIt/deployAWS/humilis/examples/layers/lambda3/meta.yaml
2017-03-29 13:03:41,290 humilis.layer INFO     Starting checks for layer vpc
2017-03-29 13:03:41,516 humilis.layer INFO     Creating layer 'vpc' (CF stack 'example-environment-vpc')
2017-03-29 13:03:41,517 humilis.layer INFO     Loading /Users/bogdan/tryIt/deployAWS/humilis/examples/layers/vpc/resources/subset1/main.json.j2
2017-03-29 13:03:41,518 humilis.layer INFO     Loading /Users/bogdan/tryIt/deployAWS/humilis/examples/layers/vpc/resources/subset2/main.json.j2
Traceback (most recent call last):
  File "/Users/bogdan/tryIt/deployAWS/bin/humilis", line 11, in <module>
    sys.exit(main())
  File "/Users/bogdan/tryIt/deployAWS/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/bogdan/tryIt/deployAWS/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/bogdan/tryIt/deployAWS/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/bogdan/tryIt/deployAWS/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/bogdan/tryIt/deployAWS/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/bogdan/tryIt/deployAWS/lib/python2.7/site-packages/humilis/cli.py", line 50, in create
    env.create(output_file=output, update=False)
  File "/Users/bogdan/tryIt/deployAWS/lib/python2.7/site-packages/humilis/environment.py", line 190, in create
    layer.create(update=update)
  File "/Users/bogdan/tryIt/deployAWS/lib/python2.7/site-packages/humilis/layer.py", line 304, in create
    self.create_with_changeset(cf_template)
  File "/Users/bogdan/tryIt/deployAWS/lib/python2.7/site-packages/humilis/layer.py", line 332, in create_with_changeset
    ChangeSetType=changeset_type)
  File "/Users/bogdan/tryIt/deployAWS/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/bogdan/tryIt/deployAWS/lib/python2.7/site-packages/botocore/client.py", line 517, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Users/bogdan/tryIt/deployAWS/lib/python2.7/site-packages/botocore/client.py", line 572, in _convert_to_request_dict
    api_params, operation_model)
  File "/Users/bogdan/tryIt/deployAWS/lib/python2.7/site-packages/botocore/validate.py", line 270, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Tags[3].Value, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>
(deployAWS) [~/tryIt/deployAWS/humilis/examples] (master)
```

Do you have any ideas why it does not work?

Best regards,
Bogdan.

**Comment by germangh** [comment]
Hi Bogdan,

Thanks for reporting this. Some of the examples are outdated and don't work anymore. In this particular case the reason for the really ugly and not informative error is that you didn't use the `--stage` option with `humilis create`. For example:

```
humilis create --stage DEV example-environment.yml
```

I'll add a test to the CLI so that users get a decent error message in the future if they don't pass the `--stage` option. I will also clean up or fix the examples in the repo but meanwhile the best way to get some up-to-date examples is to go to one of the plugin repositories (humilis-whatever) and see if there is a `tests/integration` directory. Inside you will typically find a sample environment description file that we are using as part of the integration tests for the plugin. For example:

https://github.com/humilis/humilis-kinesis-processor/blob/master/tests/integration/humilis-kinesis-processor.yaml.j2
