### ISSUE TITLE
"ConfigureParser" missing

### ISSUE THREAD

**Issue by jonapich** [InnovativeTravel/humilis#9]
`humilis configure` complains about ConfigParser (ImportError).

After installing the package, it breaks at the next step:

E:\Projects\Repos\develop\pycoveo-deploy\cloudformation\humilis>humilis configure --local
Bucket [foo]:
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\humilis.exe__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\click\core.py", line 716, in **call**
    return self.main(_args, *_kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 534, in invoke
    return callback(_args, **kwargs)
  File "c:\python27\lib\site-packages\humilis\cli.py", line 124, in configure
    config.boto_config.configure(ask=ask, local=local)
  File "c:\python27\lib\site-packages\boto3facade\config.py", line 73, in configure
    self._get_config(option, ask=ask, fallback=fallback)
  File "c:\python27\lib\site-packages\boto3facade\config.py", line 121, in _get_config
    option.replace('_', ' ').title(), val))
  File "<string>", line 0

```
^
```

SyntaxError: unexpected EOF while parsing

**Comment by germangh** [comment]
Thanks for reporting this. Actually humilis was not supporting Python 2.x, but I just made some minor changes that should make it Python 2.x compatible. Please upgrade to the latest version if you are using humilis under Python 2.x.
